"""Persistence helpers for blackboard transcriptions and resumable checkpoints."""

from __future__ import annotations

import json
from datetime import datetime


# Increment this whenever extraction/selection/transcription semantics change.
# Old cached board text is then ignored and regenerated automatically.
BLACKBOARD_CACHE_VERSION = 2
_CHECKPOINT_KEY_PREFIX = "blackboard_checkpoint:"
_CACHE_VERSION_KEY_PREFIX = "blackboard_cache_version:"
_BLACKBOARD_MARKER = "### 黑板板书 LaTeX 转写"


def _checkpoint_key(sub_id: str) -> str:
    return f"{_CHECKPOINT_KEY_PREFIX}{sub_id}"


def _cache_version_key(sub_id: str) -> str:
    return f"{_CACHE_VERSION_KEY_PREFIX}{sub_id}"


def _recover_shifted_blackboard_row(db, sub_id: str) -> tuple[str, str] | None:
    """Recover the raw board cache from a narrowly-defined schema-order bug.

    On 2026-09-10, timestamp/proofread columns were temporarily inserted into
    the middle of the fresh ``lectures`` CREATE TABLE definition while legacy
    SQLite databases gained them through ``ALTER TABLE`` (which appends them).
    The sharded reassembler still used positional ``INSERT ... SELECT *``.
    Consequently one reassembly could shift old values into later columns.

    For a blackboard lecture the signature is unusually strong: the enormous
    raw transcription beginning with ``BLACKBOARD_MARKER`` lands in
    ``emailed_at`` while ``blackboard_latex`` becomes NULL.  No legitimate
    ``emailed_at`` value can look like a 200k-character Markdown transcript, so
    this recovery is safe and intentionally limited to that exact signature.

    We restore the board cache and the two pieces of board metadata needed for
    cache reuse.  Other potentially-shifted summary fields are deliberately not
    guessed here; they can be regenerated by the normal summarization pipeline.
    """
    sid = str(sub_id)
    row = db.conn.execute(
        """SELECT blackboard_latex, blackboard_model, blackboard_at,
                  emailed_at, error_msg, error_count
           FROM lectures WHERE sub_id = ?""",
        (sid,),
    ).fetchone()
    if not row or row["blackboard_latex"]:
        return None

    misplaced = str(row["emailed_at"] or "")
    if not misplaced.startswith(_BLACKBOARD_MARKER) or len(misplaced) < 10000:
        return None

    # Under the known positional shift, old blackboard_model -> error_msg and
    # old blackboard_at -> error_count.  Use them only when plausible; the raw
    # board itself is the important asset.
    recovered_model = str(row["error_msg"] or "")
    recovered_at = str(row["error_count"] or "")
    if "T" not in recovered_at and "-" not in recovered_at:
        recovered_at = datetime.now().isoformat()

    with db._lock, db.conn:
        db.conn.execute(
            """UPDATE lectures
               SET blackboard_latex = ?,
                   blackboard_model = ?,
                   blackboard_at = ?,
                   emailed_at = NULL
               WHERE sub_id = ?""",
            (misplaced, recovered_model, recovered_at, sid),
        )
        db.conn.execute(
            """INSERT INTO meta(key, value) VALUES(?, ?)
               ON CONFLICT(key) DO UPDATE SET value = excluded.value""",
            (_cache_version_key(sid), str(BLACKBOARD_CACHE_VERSION)),
        )

    print(
        f"[Blackboard] recovered shifted raw cache for {sid}: "
        f"{len(misplaced)} chars; no vision regeneration required",
        flush=True,
    )
    return misplaced, recovered_model


def get_blackboard(db, sub_id: str) -> tuple[str, str] | None:
    """Return cached board text produced by the current extraction pipeline.

    A previous deploy bug merged ``lectures.blackboard_latex`` but dropped the
    accompanying ``meta:blackboard_cache_version:*`` key. In that situation
    the expensive transcription is still present and should be recovered
    rather than regenerated. We self-heal the missing marker once, then future
    runs use normal version checks.

    A second one-time compatibility path recovers the raw transcription from a
    known 2026-09-10 column-order shift before deciding the cache is absent.
    """
    sid = str(sub_id)
    row = db.conn.execute(
        "SELECT blackboard_latex, blackboard_model, blackboard_at "
        "FROM lectures WHERE sub_id = ?",
        (sid,),
    ).fetchone()
    if not row or not row["blackboard_latex"]:
        recovered = _recover_shifted_blackboard_row(db, sid)
        if recovered:
            return recovered
        return None

    version_row = db.conn.execute(
        "SELECT value FROM meta WHERE key = ?",
        (_cache_version_key(sid),),
    ).fetchone()
    try:
        cached_version = int(version_row["value"]) if version_row else 0
    except (TypeError, ValueError):
        cached_version = 0

    if cached_version == BLACKBOARD_CACHE_VERSION:
        return row["blackboard_latex"], row["blackboard_model"] or ""

    # Self-heal only a *missing* version marker. A non-zero mismatching marker
    # means the data was explicitly produced by an older algorithm and should
    # still be regenerated after an intentional cache-version bump.
    if cached_version == 0 and row["blackboard_at"]:
        with db._lock, db.conn:
            db.conn.execute(
                """INSERT INTO meta(key, value) VALUES(?, ?)
                   ON CONFLICT(key) DO UPDATE SET value = excluded.value""",
                (_cache_version_key(sid), str(BLACKBOARD_CACHE_VERSION)),
            )
        print(
            f"[Blackboard] recovered existing cache for {sid}; "
            "restored missing cache-version metadata",
            flush=True,
        )
        return row["blackboard_latex"], row["blackboard_model"] or ""

    return None


def save_blackboard(db, sub_id: str, markdown: str, model: str) -> None:
    """Persist the final chronological Markdown+LaTeX transcription."""
    with db._lock, db.conn:
        db.conn.execute(
            """UPDATE lectures
               SET blackboard_latex = ?, blackboard_model = ?, blackboard_at = ?
               WHERE sub_id = ?""",
            (markdown, model, datetime.now().isoformat(), str(sub_id)),
        )
        db.conn.execute(
            """INSERT INTO meta(key, value) VALUES(?, ?)
               ON CONFLICT(key) DO UPDATE SET value = excluded.value""",
            (_cache_version_key(str(sub_id)), str(BLACKBOARD_CACHE_VERSION)),
        )
        db.conn.execute(
            "DELETE FROM meta WHERE key = ?",
            (_checkpoint_key(str(sub_id)),),
        )


def load_blackboard_checkpoint(db, sub_id: str, sample_sec: int) -> list[dict]:
    """Load successful per-frame vision results from a previous interrupted run."""
    row = db.conn.execute(
        "SELECT value FROM meta WHERE key = ?",
        (_checkpoint_key(str(sub_id)),),
    ).fetchone()
    if not row or not row["value"]:
        return []
    try:
        payload = json.loads(row["value"])
    except (TypeError, ValueError, json.JSONDecodeError):
        return []
    if int(payload.get("version", -1)) != BLACKBOARD_CACHE_VERSION:
        return []
    if int(payload.get("sample_sec", -1)) != int(sample_sec):
        return []
    results = payload.get("results", [])
    return results if isinstance(results, list) else []


def save_blackboard_checkpoint(db, sub_id: str, sample_sec: int, results: list[dict]) -> None:
    """Persist successful frame results after each vision batch."""
    payload = json.dumps(
        {
            "version": BLACKBOARD_CACHE_VERSION,
            "sample_sec": int(sample_sec),
            "updated_at": datetime.now().isoformat(),
            "results": results,
        },
        ensure_ascii=False,
        separators=(",", ":"),
    )
    with db._lock, db.conn:
        db.conn.execute(
            """INSERT INTO meta(key, value) VALUES(?, ?)
               ON CONFLICT(key) DO UPDATE SET value = excluded.value""",
            (_checkpoint_key(str(sub_id)), payload),
        )


def clear_blackboard_checkpoint(db, sub_id: str) -> None:
    with db._lock, db.conn:
        db.conn.execute(
            "DELETE FROM meta WHERE key = ?",
            (_checkpoint_key(str(sub_id)),),
        )
